name: save_point_app
description: 'A toolbox for snapshot game progress and counter autosave system and save slot limits.'
publish_to: 'none'
version: 0.8.0

environment:
  sdk: ^3.8.1

dependencies:
  archive: ^4.0.7
  flutter:
    sdk: flutter
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
